-- Base de datos creada con la version de MySQL 8.0.

USE CHATIO;

-- EJECUTAR ESTA LINEA CON PERMISOS DE SUPER-USUARIO.
-- SET GLOBAL log_bin_trust_function_creators = 1;

DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS
(
    CODE INT AUTO_INCREMENT
    ,USERNAME NVARCHAR(30)
    ,PASSWORD NVARCHAR(30)
    ,EMAIL NVARCHAR(50)
    ,CONSTRAINT PK_USERS_CODE PRIMARY KEY (CODE)
    ,CONSTRAINT NN_USERS_USERNAME CHECK ( USERNAME IS NOT NULL )
    ,CONSTRAINT NN_USERS_PASSWORD CHECK ( PASSWORD IS NOT NULL )
    ,CONSTRAINT NN_USERS_EMAIL CHECK ( EMAIL IS NOT NULL )
    ,CONSTRAINT UQ_USERS_USERNAME UNIQUE ( USERNAME )
    ,CONSTRAINT UQ_USERS_EMAIL UNIQUE ( EMAIL )
);

ALTER TABLE USERS ADD INDEX ( USERNAME );


-- DROP PROCEDURE IF EXISTS InsertUser;

DELIMITER //
CREATE PROCEDURE InsertUser
(
    IN in_username NVARCHAR(30)
    ,IN in_password NVARCHAR(30)
    ,IN in_email NVARCHAR(50)
)
BEGIN
	INSERT
	    INTO
            USERS
	        ( USERNAME, PASSWORD, EMAIL )
	    VALUES
            ( in_username, in_password, in_email );
END //
DELIMITER ;


-- DROP FUNCTION IF EXISTS Login;

CREATE FUNCTION Login(in_username NVARCHAR(30), in_password NVARCHAR(30))
RETURNS BIT DETERMINISTIC
BEGIN
    IF EXISTS(SELECT * FROM USERS WHERE USERNAME = in_username AND PASSWORD = in_password) THEN
        RETURN 1;
    ELSE
        RETURN 0;
    END IF;
END;

-- Inserts de prueba
